#!/bin/bash

for i in \
    airy \
    aitoff \
    armadillo \
    august \
    baker \
    berghaus \
    boggs \
    bonne \
    bottomley \
    bromley \
    chamberlin \
    collignon \
    craig \
    craster \
    cylindricalEqualArea \
    cylindricalStereographic \
    eckert1 \
    eckert2 \
    eckert3 \
    eckert4 \
    eckert5 \
    eckert6 \
    eisenlohr \
    fahey \
    foucaut \
    gilbert \
    gingery \
    ginzburg4 \
    ginzburg5 \
    ginzburg6 \
    ginzburg8 \
    ginzburg9 \
    gringorten \
    gringortenQuincuncial \
    guyou \
    kavrayskiy7 \
    larrivee \
    laskowski \
    littrow \
    loximuthal \
    miller \
    modifiedStereographicAlaska \
    modifiedStereographicGs48 \
    modifiedStereographicGs50 \
    modifiedStereographicMiller \
    modifiedStereographicLee \
    mollweide \
    mtFlatPolarParabolic \
    mtFlatPolarQuartic \
    mtFlatPolarSinusoidal \
    naturalEarth \
    nellHammer \
    patterson \
    pierceQuincuncial \
    polyconic \
    rectangularPolyconic \
    robinson \
    satellite \
    sinuMollweide \
    sinusoidal \
    times \
    vanDerGrinten \
    vanDerGrinten2 \
    vanDerGrinten3 \
    vanDerGrinten4 \
    wagner4 \
    wagner6 \
    wagner7 \
    wiechel \
    winkel3 \
    ; do
  test/render-world $i \
      && [ "$(compare -metric rmse img/$i.png test/output/$i.png null: 2>&1)" = "0 (0)" ] \
      || echo "✗ test/output/$i.png and img/$i.png differ"
done
