#!/bin/bash

for i in \
    airy \
    aitoff \
    armadillo \
    august \
    baker \
    berghaus \
    boggs \
    bonne \
    bottomley \
    bromley \
    chamberlin \
    collignon \
    craig \
    craster \
    cylindricalEqualArea \
    cylindricalStereographic \
    eckert1 \
    eckert2 \
    eckert3 \
    eckert4 \
    eckert5 \
    eckert6 \
    eisenlohr \
    fahey \
    foucaut \
    gilbert \
    gingery \
    ginzburg4 \
    ginzburg5 \
    ginzburg6 \
    ginzburg8 \
    ginzburg9 \
    gringorten \
    gringortenQuincuncial \
    guyou \
    mollweide \
    pierceQuincuncial \
    sinusoidal \
    winkel3 \
    ; do
  test/compute-scale $i
done
