#!/bin/bash

for i in \
    aitoff \
    airy \
    armadillo \
    august \
    baker \
    berghaus \
    mollweide; do
  test/render-world $i \
      && [ "$(compare -metric rmse img/$i.png test/output/$i.png null: 2>&1)" = "0 (0)" ] \
      || echo "✗ test/output/$i.png and img/$i.png differ"
done
