#!/usr/bin/env node

var width = 960,
    height = 500,
    projectionName = process.argv[2],
    projectionSymbol = "geo" + projectionName[0].toUpperCase() + projectionName.slice(1);

if (!/^[a-z0-9]+$/i.test(projectionName)) throw new Error;

var fs = require("fs"),
    topojson = require("topojson"),
    Canvas = require("canvas"),
    d3 = require("d3"),
    d3_geo = require("d3-geo"),
    d3_geo_projection = require("../");

var canvas = new Canvas(width, height),
    context = canvas.getContext("2d");

var world = require("./data/world-50m.json"),
    land = topojson.feature(world, world.objects.land),
    graticule = d3_geo.geoGraticule(),
    outline = {type: "Sphere"};

switch (projectionName) {
  case "littrow": outline = graticule.extent([[-90, -60], [90, 60]]).outline(); break;
  case "modifiedStereographicGs50": outline = graticule.extent([[-180, 15], [-50, 75]]).outline(); break;
}

var path = d3_geo.geoPath()
    .projection(d3_geo_projection[projectionSymbol]().precision(0.1))
    .context(context);

context.fillStyle = "#fff";
context.fillRect(0, 0, width, height);
context.save();

switch (projectionName) {
  case "armadillo":
  case "berghaus":
  case "gingery":
  case "hammerRetroazimuthal":
  case "healpix":
  case "littrow":
  case "modifiedStereographicGs50": {
    context.beginPath();
    path(outline);
    context.clip();
    break;
  }
}

context.beginPath();
path(land);
context.fillStyle = "#000";
context.fill();

context.beginPath();
path(graticule());
context.strokeStyle = "rgba(119,119,119,0.5)";
context.stroke();

context.restore();

context.beginPath();
path(outline);
context.strokeStyle = "#000";
context.stroke();

console.warn("↳ test/output/" + projectionName + ".png");
canvas.pngStream().pipe(fs.createWriteStream("test/output/" + projectionName + ".png"));
